/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author RIHS
 */
public class TelaPrincipal extends javax.swing.JFrame {
    ArrayList<Integer> numeros = new ArrayList(); // Lista de números a serem sorteados simulando o globo de sorteio
    Random aleatorio;  // para gerar numeros aleatorios
    int quantidadeFaltante = 0;   // Para Saber quantos números ainda faltam para ser sorteado
    int ordem = 0;  //ordenação do soreio, meramente para exibir qual a posição foi sorteado, primeiro, segundo, etc...
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        this.b_sortear.setEnabled(false);  // Desabilita o Botão para evitar que inicie o sorteio sem saber a quantidade de números.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_numerosorteado = new javax.swing.JLabel();
        c_entrada = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        a_saida = new javax.swing.JTextArea();
        b_novo = new javax.swing.JButton();
        b_sortear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sorteio");

        l_numerosorteado.setFont(new java.awt.Font("Segoe UI", 1, 144)); // NOI18N
        l_numerosorteado.setText("0");
        l_numerosorteado.setPreferredSize(new java.awt.Dimension(20, 26));

        c_entrada.setToolTipText("");

        a_saida.setColumns(20);
        a_saida.setRows(5);
        jScrollPane1.setViewportView(a_saida);

        b_novo.setText("Novo");
        b_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_novoActionPerformed(evt);
            }
        });

        b_sortear.setText("Sortear");
        b_sortear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_sortearActionPerformed(evt);
            }
        });

        jLabel2.setText("Quantidade de números:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(l_numerosorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(66, 66, 66)
                        .addComponent(c_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b_novo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(b_sortear)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_novo)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(l_numerosorteado, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(b_sortear)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_novoActionPerformed
        int quantidade = Integer.parseInt(this.c_entrada.getText());
        numeros.clear();
        if (quantidade<=0){
            JOptionPane.showMessageDialog(null, "Valor deve ser maior que 0");
        }else{
            for(int i=1;i<=quantidade;i++){
                numeros.add(i);
            }
            quantidadeFaltante = quantidade;
            this.b_sortear.setEnabled(true);
            this.b_novo.setEnabled(false);
        }
    }//GEN-LAST:event_b_novoActionPerformed

    private void b_sortearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sortearActionPerformed
        if(!numeros.isEmpty()){  // Se existe números a serem sorteados faça
            aleatorio = new Random(); //Cria um novo Random
            int indice = aleatorio.nextInt(quantidadeFaltante); //pega um número aleatório entre 0 e o valor de quantidadeFaltante
            quantidadeFaltante--; //depois do sorteio retira a quantidade restante em -1
            ordem++; // indica qual a posição que foi sorteado, primeiro, segundo, etc.
            a_saida.append(ordem+"º sorteado: "+numeros.get(indice).toString()+"\n"); // Adiciona o numero sorteado no  JTextArea
            l_numerosorteado.setText(numeros.get(indice).toString()); //Mostra o número sorteado por meio do Label
            numeros.remove(indice); // Remove o número
        }else{ //Se acabou os numeros a serem sorteados
            JOptionPane.showMessageDialog(null, "Não Há números a serem sorteados \n inicie um novo Sorteio");
            this.b_novo.setEnabled(true);  // habilita o botão novo
            this.b_sortear.setEnabled(false); // desabilita o botão sortear
        }
    }//GEN-LAST:event_b_sortearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea a_saida;
    private javax.swing.JButton b_novo;
    private javax.swing.JButton b_sortear;
    private javax.swing.JTextField c_entrada;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_numerosorteado;
    // End of variables declaration//GEN-END:variables
}
